version: "3"
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - task -d ../long_short_pair_calculator build || exit 1
      - soroban contract build --package long_short_pair
      - soroban contract optimize --wasm ../../target/wasm32v1-none/release/long_short_pair.wasm --wasm-out ../../target/wasm32v1-none/release/long_short_pair.wasm
      - cp ../../target/wasm32v1-none/release/long_short_pair.wasm ../../wasm/long_short_pair.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
