version: "3"
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - task -d ../config_storage build || exit 1
      - task -d ../rewards_gauge build || exit 1
      - task -d ../liquidity_pool build || exit 1
      - task -d ../liquidity_pool_stableswap build || exit 1
      - task -d ../liquidity_pool_liquidity_calculator build || exit 1
      - soroban contract build --package liquidity_pool_router
      - soroban contract optimize --wasm ../../target/wasm32v1-none/release/liquidity_pool_router.wasm --wasm-out ../../target/wasm32v1-none/release/liquidity_pool_router.wasm
      - cp ../../target/wasm32v1-none/release/liquidity_pool_router.wasm ../../wasm/liquidity_pool_router.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
