version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - soroban contract build --package token-long-short-pair
      - soroban contract optimize --wasm ../../target/wasm32v1-none/release/token_long_short_pair.wasm --wasm-out ../../target/wasm32v1-none/release/token_long_short_pair.wasm
      - cp ../../target/wasm32v1-none/release/token_long_short_pair.wasm ../../wasm/token_long_short_pair.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
