version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - soroban contract build --package liquidity_pool_plane
      - soroban contract optimize --wasm ../../target/wasm32v1-none/release/liquidity_pool_plane.wasm --wasm-out ../../target/wasm32v1-none/release/liquidity_pool_plane.wasm
      - cp ../../target/wasm32v1-none/release/liquidity_pool_plane.wasm ../../wasm/liquidity_pool_plane.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
