version: "3"
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - task -d ../config_storage build || exit 1
      - soroban contract build --package rewards_gauge
      - soroban contract optimize --wasm ../../target/wasm32v1-none/release/rewards_gauge.wasm --wasm-out ../../target/wasm32v1-none/release/rewards_gauge.wasm
      - cp ../../target/wasm32v1-none/release/rewards_gauge.wasm ../../wasm/rewards_gauge.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
